kind: Service
apiVersion: v1
metadata:
  name: {{ template "geth-helm.name" . }}-service
  labels:
    app: {{ template "geth-helm.name" . }}
    chart: {{ template "geth-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "geth-helm.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - name: rpc
    port: 8545
