apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
    - name: commit-semantics-check
      context: "commit-semantics-check"
      always_run: true
      optional: false
      source: "semanticcheck.yaml"
    - name: pr
      context: "pr"
      always_run: true
      optional: false
      source: "pullrequest.yaml"
  postsubmits:
    - name: release
      context: "release"
      source: "release.yaml"
      branches:
        - ^main$
        - ^master$
